# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
name: فرهاد بیگی راد
showname: فرهاد بیگی‌راد
name-en: Farhad Beigirad
keywords:
  - فرهاد بیگی راد
  - بیگی راد
  - فرهاد راد
  - بیگی‌راد
  - beigirad
  - f.beigirad
bio: >-
  متولد مهر ۷۴ ، توسعه دهنده‌ی اندروید ،
  دانشجوی کارشناسی نرم‌افزار و علاقمند به تازه‌های دنیای نرم‌افزار
description: >-
  خلاصه ای از آموخته ها و تجربه های من از برنامه نویسی فرهاد بیگی‌راد
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://beigirad.ir" # the base hostname & protocol for your site, e.g. http://example.com

#permalink: /:categories/:year-:month-:day/:title.html
permalink: /:categories/:title.html
paginate: false

disqus:
   shortname: beigirad

# if you don't have any of social below, comment the line
#facebook: myfacebook
twitter: feri_dom
email: beigirad@gmail.com
# google: mygoogle
# instagram: myinstagram
# pinterest: mypinterest
linkedin: beigirad
# youtube: myyoutube
# spotify: myspotify
github: beigirad
# lastfm: mylastfm
# stackoverflow: 7044681/mystackoverflow
# quora: userquora
#reddit: username
#medium: medium
# vimeo: myvimeo
# lanyrd: mylanyrd
telegram: beigirad


# do you want a larger site? change the option below
# options: [normal, large] | default: normal
# normal = 560px / large = 810px
width: normal

# Build settings
markdown: kramdown
# theme: theme
plugins:
  - jekyll-feed
  - jekyll-sitemap


# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - node_modules
  - gulpfile.js
  - package.json
  - Gemfile
  - Gemfile.lock
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
